"""initial_schema_baseline

Revision ID: d32bec0b796e
Revises: 
Create Date: 2026-10-02 10:27:44.002924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32bec0b796e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('plan_tier', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_rules', sa.Integer(), nullable=False),
    sa.Column('max_monthly_events', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('automation_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_json', sa.Text(), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=False),
    sa.Column('actions_json', sa.Text(), nullable=False),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rules_organization_id'), ['organization_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('organization_usages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'period', name='uq_org_period')
    )
    with op.batch_alter_table('organization_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_usages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_usages_period'), ['period'], unique=False)

    op.create_table('system_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('endpoint_token', sa.String(length=64), nullable=False),
    sa.Column('secret_token', sa.String(length=64), nullable=True),
    sa.Column('target_rule_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('last_received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_rule_id'], ['automation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_endpoint_token'), ['endpoint_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_organization_id'), ['organization_id'], unique=False)

    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('trigger_event', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('is_dry_run', sa.Boolean(), nullable=False),
    sa.Column('input_payload_json', sa.Text(), nullable=False),
    sa.Column('condition_trace_json', sa.Text(), nullable=False),
    sa.Column('action_results_json', sa.Text(), nullable=False),
    sa.Column('steps_trace_json', sa.Text(), nullable=False),
    sa.Column('ai_result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_rule_id'), ['rule_id'], unique=False)

    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['automation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_steps_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('execution_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_data_json', sa.Text(), nullable=False),
    sa.Column('output_data_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_steps_execution_id'), ['execution_id'], unique=False)

    op.create_table('incident_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_summary_json', sa.Text(), nullable=True),
    sa.Column('acknowledged_by_id', sa.String(length=64), nullable=True),
    sa.Column('resolved_by_id', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_alerts_organization_id'), ['organization_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('route_department', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_organization_id'))
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))

    op.drop_table('leads')
    with op.batch_alter_table('incident_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_alerts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_incident_alerts_created_at'))

    op.drop_table('incident_alerts')
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_steps_execution_id'))

    op.drop_table('execution_steps')
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_workflow_id'))

    op.drop_table('workflow_steps')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_executions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_executed_at'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_organization_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_endpoint_token'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_system_events_event_name'))
        batch_op.drop_index(batch_op.f('ix_system_events_created_at'))

    op.drop_table('system_events')
    with op.batch_alter_table('organization_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_usages_period'))
        batch_op.drop_index(batch_op.f('ix_organization_usages_organization_id'))

    op.drop_table('organization_usages')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_rules_organization_id'))

    op.drop_table('automation_rules')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_organization_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
